apiVersion: v1
kind: Pod
metadata:
  name: k8s-jenkins
  labels:
    name: k8s-jenkins
spec:
  containers:
  - name: k8s-jenkins
    image: ducdoan123/jenkins-cdb-sync:v1
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    env:
    - name: DB_HOST
      value: db.default.svc.cluster.local
    - name: DB_PORT
      value: '5432'
    - name: DB_NAME
      value: student
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: DB_USERNAME
    - name: DB_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: DB_PASSWORD
    command: ["/bin/sh"]
    args: [-c "echo Jenkins job finish running at $(date) | mail doan_d1@denison.edu" ]

    ports:
      - containerPort: 8099
  restartPolicy: OnFailure
