version: '2'
networks:
 kafka-net:
   name: kafka-net
   driver: bridge

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=student
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - kafka-net

  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    networks:
      - kafka-net
  # sb:
  #   depends_on:
  #   - "db"
  #   - "cache"
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USER=${DB_USERNAME}
  #     - DB_NAME=student
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - KAFKA_BROKERCONNECT=kafka1:29092,kafka2:29093,kafka3:29094
  #     - JVM_OPTS=-Xms32M -Xmx64M
  #     - SERVER_SERVLET_CONTEXTPATH=/
  #     - REDIS_HOST=cache
  #   build: 
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8085:8085"
  #   restart: on-failure:10`
  #   networks:
  #     - kafka-net

#Zookeeper Service.
#Image Tag: bitnami/zookeeper:3.6.2

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: "no"
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper
    networks:
      - kafka-net

#Kafka Service
#Image Tag: bitnami/kafka:2.7.0
# sed -i 's/^offset.retention.minutes=.*/offset.retention.minutes=1/' /opt/bitnami/kafka/config/server.properties && configs:
#/opt/bitnami/ctlscript.sh restart kafka"
# /opt/bitnami/kafka/bin/kafka-configs.sh --bootstrap-server kafka2:29093 --alter --entity-type topics --entity-name kafka.cache-wt --add-config retention.ms=1440000

  kafka1:
    image: 'bitnami/kafka:latest'
    restart: "no"
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      
    container_name: kafka-broker1
    
    depends_on:
      - "zookeeper"
    networks:
      - kafka-net
      
  kafka2:
    image: 'bitnami/kafka:latest'
    restart: "no"
    ports:
      - '9093:9093'
      - '29093:29093'
      
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29093,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:29093,EXTERNAL://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      
    container_name: kafka-broker2
    
    depends_on:
      - "zookeeper"
    networks:
      - kafka-net

    
  kafka3:
    image: 'bitnami/kafka:latest'
    restart: "no"
    ports:
      - '9094:9094'
      - '29094:29094'
      
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29094,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:29094,EXTERNAL://localhost:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      
    container_name: kafka-broker3
    
    depends_on:
      - "zookeeper"
    networks:
      - kafka-net

  kafka-partitions:
    image: 'bitnami/kafka:latest'
    ports:
      - '9095:9095'
    #command set topic wtih configs + add retentions for topic to get rid of error message 
    command: >
      /bin/bash -c "/opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server kafka2:29093 --replication-factor 2 --partitions 3 --if-not-exists --topic kafka.cache-wt &&
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server kafka2:29093 --replication-factor 2 --partitions 3 --if-not-exists --topic kafka.postgres-modify"

    networks:
      - kafka-net  
#KafDrop UI for management
#Image Tag: obsidiandynamics/kafdrop:3.27.0
#Open localhost:9000 once docker compose up to pull image finish

  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    restart: "no"
    ports:
      - 9000:9000
    
    environment:
      - KAFKA_BROKERCONNECT=kafka1:29092,kafka2:29093,kafka3:29094
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    
    container_name: kafdrop
    depends_on:
      - "kafka1"
      - "kafka2"
      - "kafka3"
    networks:
      - kafka-net
      