apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sb
spec:
  selector:
    matchLabels:
      app: k8s-sb
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-sb
    spec:
      # restartPolicy: Never
      containers:
      - name: k8s-sb
        image: ducdoan123/sb_v1:v1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8085
        env:
        - name: DB_HOST
          value: db.default.svc.cluster.local
        - name: DB_PORT
          value: '5432'
        - name: DB_NAME
          value: student
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: ducdoanp0stgre
        - name: REDIS_HOST
          value: cache
        - name: KAFKA_BROKERCONNECT
          value: kafka1:29092,kafka2:29093,kafka3:29094
        # - name: JVM_OPTS
        #   value: -Xms32M -Xmx64M
        # - name: SERVER_SERVLET_CONTEXTPATH
        #   value: /
        # - name: REDIS_HOST
        #   value: cache
      # hostNetwork: true

# livenessProbe:
#   httpGet:
#     path: /_status/healthz
#     port: 5000
#   initialDelaySeconds: 90
#   timeoutSeconds: 10
# readinessProbe:
#   httpGet:
#     path: /_status/healthz
#     port: 5000
#   initialDelaySeconds: 30
#   timeoutSeconds: 10
# env:
# - name:  ENVVARNAME
#   value:  ENVVARVALUE   
#   volumeMounts:
#   - mountPath: /data
#     name: data
# volumes:
#   - name: data
#     emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-sb-serv
spec:
  type: LoadBalancer
  selector:
    app: k8s-sb
  ports:
  - port: 8085
    targetPort: 8085
